### PR TITLE
Added Features in Readme

### PR DESCRIPTION
**Pull request by itskdhere**
Added the list of features in README.md file 🙂

### CODE REVIEW

**Comment by itsme-Subid** [comment]
instead of features, u can list down the routes, their methods, their arguments, and its types

**Comment by itskdhere** [comment]
> instead of features, u can list down the routes, their methods, their arguments, and its types

@itsme-Subid I'll open a new PR for that :)

**Review by itsme-Subid — CHANGES_REQUESTED** [review]
every point should have `-`, keep the spacing evenly and same throughout the file

**Comment by itskdhere** [comment]
> every point should have `-`, keep the spacing evenly and same throughout the file

@itsme-Subid  Done 👍

**Review by itsme-Subid — APPROVED** [review]
its good but the emojis was better, anyways its all good

**Pull request merged**
